name: giv_flutter
description: Project code name GIV - Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.11.19+4039

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.0.0
  country_code_picker: ^2.0.1
  faker: ^2.0.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter_facebook_auth: ^4.0.1
  flutter_svg: ^1.0.3
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  http: ^0.13.1
  http_multi_server: ^3.0.0
  image_cropper: ^1.0.2
  image_picker: ^0.8.4+7
  package_info: ^2.0.0
  photo_view: ^0.13.0
  pin_code_fields: ^7.0.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.5
  share: ^2.0.1
  sign_in_with_apple: ^3.3.0
  url_launcher: ^6.0.3
  uuid: ^3.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.0.1
  build_runner: ^2.1.7
  mockito: ^5.0.3
  test: ^1.14.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/mailbox.svg
    - images/logo.svg
    - images/undraw_empty_posts.svg
    - images/undraw_notify_orange.svg
    - images/undraw_my_location.svg
    - images/undraw_synchronize_1e88e5.svg
    - images/undraw_thoughts_2196f3.svg
    - images/user_bw.svg
    - images/undraw_team.svg
    - images/undraw_i_can_fly.svg
    - images/undraw_app_giving.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Overpass
      fonts:
        - asset: fonts/Overpass-Regular.ttf
        - asset: fonts/Overpass-Bold.ttf
          weight: 700
