name: giv_flutter
description: Project code name GIV - Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.11.5+31

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^2.0.0
  country_code_picker: ^1.1.7
  faker: ^1.1.1
  firebase_auth: ^0.11.1+10
  firebase_core: ^0.4.0+6
  firebase_storage: ^3.0.3
  flutter_facebook_login: ^3.0.0
  flutter_svg: ^0.19.3
  google_sign_in: ^4.0.4
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  http: ^0.12.0+2
  http_multi_server: ^2.2.0
  image_cropper: ^1.0.2
  image_picker: ^0.6.0+17
  photo_view: ^0.4.2
  pin_code_fields: ^4.0.0
  provider: ^5.0.0 # Used for dependency injection
  rxdart: ^0.22.0
  shared_preferences: ^0.5.3+4
  share: '>=0.6.5+2 <2.0.0'
  sign_in_with_apple: ^2.5.4
  url_launcher: ^5.4.2
  uuid: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.8.1
  build_runner: ^1.10.1
  mockito: ^4.1.1
  test: ^1.14.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/mailbox.svg
    - images/logo.svg
    - images/undraw_empty_posts.svg
    - images/undraw_notify_orange.svg
    - images/undraw_my_location.svg
    - images/undraw_synchronize_1e88e5.svg
    - images/undraw_thoughts_2196f3.svg
    - images/user_bw.svg
    - images/undraw_team.svg
    - images/undraw_i_can_fly.svg
    - images/undraw_app_giving.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
   - family:  CustomIcons
     fonts:
      - asset: fonts/CustomIcons.ttf
   - family:  Overpass
     fonts:
     - asset: fonts/Overpass-Regular.ttf
     - asset: fonts/Overpass-Bold.ttf
       weight: 700
