/// Flutter icons CustomIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData ib_le_magnifying_glass = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ib_le_house = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ib_le_chatv2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ib_b_trust = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ib_b_team = const IconData(0xe804, fontFamily: _kFontFam);
}
