name: GitHub Actions Demo
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Inatall Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.10.0

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Format files
        run: flutter format --set-exit-if-changed .

      - name: Build runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze files
        run: flutter analyze --no-pub --no-current-package lib/ test/

      - name: Run the tests
        run: flutter test --coverage --coverage-path=lcov.info
